#!/bin/bash

set -e
source "$(dirname "$(readlink -f "$0")")/dxp.config"

dxp-test-setup

keytool -genkey -v -keystore keystore -storepass android -alias ket -keypass android -keyalg RSA -validity 36500

