#!/bin/bash

set -e
source "$(dirname "$(readlink -f "$0")")/dxp.config"

dxp-test-setup

java -jar "$dxp_dexpatcher_jar" --verbose --output patched.dex source.dex patch.dex

# This jar is not needed:
#d2j-dex2jar.sh --force --output patched.jar patched.dex

cp patched.dex decode/classes.dex
apktool build --use-aapt2 --output patched.apk decode/


zipalign -p -f 4 patched.apk patched-aligned.apk
mv patched-aligned.apk patched.apk

apksigner sign -ks keystore --ks-pass pass:android -ks-key-alias key patched.apk


echo "dxp-make-patched: done: patched.apk"

